CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    phone_number VARCHAR2(20),
    address VARCHAR2(200),
    city VARCHAR2(100),
    state VARCHAR2(50),
    zip_code VARCHAR2(20),
    country VARCHAR2(100),
    CONSTRAINT customers_pk PRIMARY KEY (customer_id)
);

CREATE TABLE piratecoin_url (
    url_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    url VARCHAR2(500),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR2(200),
    user_id NUMBER,
    CONSTRAINT piratecoin_url_pk PRIMARY KEY (url_id),
    CONSTRAINT piratecoin_url_fk FOREIGN KEY (user_id) REFERENCES customers(customer_id)
);

CREATE TABLE movies (
    movie_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(200),
    release_date DATE,
    director VARCHAR2(100),
    genre VARCHAR2(100),
    duration_minutes NUMBER,
    CONSTRAINT movies_pk PRIMARY KEY (movie_id)
);

CREATE TABLE series (
    series_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(200),
    release_date DATE,
    director VARCHAR2(100),
    genre VARCHAR2(100),
    num_seasons NUMBER,
    num_episodes NUMBER,
    CONSTRAINT series_pk PRIMARY KEY (series_id)
);

CREATE TABLE seriesepisodes (
    episode_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR(100).
    release_date DATE,
    bloc_url VARCHAR (50),
    seriesid NUMBER,
    CONSTRAINT episodes_pk PRIMARY KEY (episode_id)
);

CREATE TABLE wallets (
wallet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
user_id NUMBER(20),
value_id,
CONSTRAINT wallets_pk PRIMARY KEY (wallet_id)
);

CREATE TABLE XCHANGERATES (
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
XCHANGEDATE DATE,
Rate NUMBER,
USD NUMBER,
KES NUMBER,
EUR NUMBER,
GBP NUMBER,
PIRATECOIN NUMBER,
CONSTRAINT xchangerate_pk PRIMARY KEY (ID)
);
